export default {
  CREATE_MEETUP_REQUEST: '@meetup/CREATE_MEETUP_REQUEST',
  CREATE_MEETUP_SUCCESS: '@meetup/CREATE_MEETUP_SUCCESS',
  CREATE_MEETUP_FAILURE: '@meetup/CREATE_MEETUP_FAILURE',
  UPDATE_MEETUP_REQUEST: '@meetup/UPDATE_MEETUP_REQUEST',
  UPDATE_MEETUP_SUCCESS: '@meetup/UPDATE_MEETUP_SUCCESS',
  UPDATE_MEETUP_FAILURE: '@meetup/UPDATE_MEETUP_FAILURE',
  CANCEL_MEETUP_REQUEST: '@meetup/CANCEL_MEETUP_REQUEST',
  CANCEL_MEETUP_SUCCESS: '@meetup/CANCEL_MEETUP_SUCCESS',
  CANCEL_MEETUP_FAILURE: '@meetup/CANCEL_MEETUP_FAILURE',
};
